export const english = [
    { "quote": "The only person you are destined to become is the person you decide to be." },
    { "quote": "The journey of a thousand miles begins with a single step." },
    { "quote": "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart." },
    { "quote": "It is during our darkest moments that we must focus to see the light." },
    { "quote": "Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do. So throw off the bowlines, sail away from safe harbor, catch the trade winds in your sails. Explore, Dream, Discover." },
    { "quote": "You don't have to be great to start, but you have to start to be great." },
    { "quote": "The difference between ordinary and extraordinary is that little extra." },
    { "quote": "Believe you can and you're halfway there." },
    { "quote": "The mind is everything. What you think you become." },
    { "quote": "Our greatest glory is not in never falling, but in rising every time we fall." },
    { "quote": "The future belongs to those who believe in the beauty of their dreams." },
    { "quote": "The only limit to our realization of tomorrow will be our doubts of today." },
    { "quote": "The best way to predict the future is to create it." },
    { "quote": "A ship in harbor is safe, but that is not what ships are built for." },
    { "quote": "Where there is a will, there is a way." },
    { "quote": "You miss 100% of the shots you don't take." },
    { "quote": "The only way to do great work is to love what you do." },
    { "quote": "If you can dream it, you can do it." },
    { "quote": "The best time to plant a tree was 20 years ago. The second best time is now." },
    { "quote": "Kindness is a language that everyone understands." },
    { "quote": "A goal without a plan is just a wish." },
    { "quote": "It's not what happens to you, but how you react that matters." },
    { "quote": "The only person you are destined to compete with is the person you were yesterday." },
    { "quote": "Life is not measured by the number of breaths you take, but by the moments that take your breath away." },
    { "quote": "Failure is simply the opportunity to begin again, this time more intelligently." },
    { "quote": "Learning is a treasure that will follow its owner everywhere." },
    { "quote": "A river cuts through rock, not because of its power, but because of its persistence." },
    { "quote": "The best and most beautiful things in the world cannot be seen, nor even touched - they must be felt with the heart." },
    { "quote": "Challenges are what make life interesting and overcoming them is what makes life meaningful." },
    { "quote": "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well." },
    { "quote": "Let us never forget that government is ourselves and not an alien power over us. The ultimate rulers of our democracy are not a handful of politicians, but the millions of men and women who cast the ballot." },
    { "quote": "Education is the most powerful weapon which you can use to change the world." },
    { "quote": "The only true wisdom is in knowing you know nothing." },
    { "quote": "The important thing is not to stop questioning. Curiosity has its own reason for existing." },
    { "quote": "The unexamined life is not worth living." },
    { "quote": "Without music, life would be a mistake." },
    { "quote": "He who has health has hope; and he who has hope has everything." },
    { "quote": "Life is 10% what happens to you and 90% how you react to it." },
    { "quote": "The journey of a thousand miles begins with a single step." },
    { "quote": "You don't have to be great to start, but you have to start to be great." },
    { "quote": "The mind is everything. What you think you become." },
    { "quote": "The future belongs to those who believe in the beauty of their dreams." },
    { "quote": "The only limit to our realization of tomorrow will be our doubts of today." },
    { "quote": "The best way to predict the future is to create it." },
    { "quote": "You miss 100% of the shots you don't take." },
    { "quote": "The only way to do great work is to love what you do." },
    { "quote": "The only way to do great work is to love what you do. - Steve Jobs" },
    { "quote": "In the end, it's not the years in your life that count. It's the life in your years. - Abraham Lincoln" },
    { "quote": "Believe you can and you're halfway there. - Theodore Roosevelt" },
    { "quote": "It does not matter how slowly you go as long as you do not stop. - Confucius" },
    { "quote": "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt" },
    { "quote": "It is never too late to be what you might have been. - George Eliot" },
    { "quote": "The best way to predict the future is to create it. - Peter Drucker" },
    { "quote": "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela" },
    { "quote": "Your time is limited, don't waste it living someone else's life. - Steve Jobs" },
    { "quote": "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill" },
    { "quote": "The only thing necessary for the triumph of evil is for good men to do nothing. - Edmund Burke" },
    { "quote": "Life is what happens when you're busy making other plans. - John Lennon" },
    { "quote": "It always seems impossible until it's done. - Nelson Mandela" },
    { "quote": "Happiness is not something ready made. It comes from your own actions. - Dalai Lama" },
    { "quote": "The way to get started is to quit talking and begin doing. - Walt Disney" },
    { "quote": "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt" },
    { "quote": "Stay hungry, stay foolish. - Steve Jobs" },
    { "quote": "In the midst of chaos, there is also opportunity. - Sun Tzu" },
    { "quote": "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll" },
    { "quote": "Don't watch the clock; do what it does. Keep going. - Sam Levenson" },
    { "quote": "You miss 100% of the shots you don't take. - Wayne Gretzky" }
]